# ワークフローの名前
name: Golangci-lint ReviewDog 

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches-ignore:
      - main

jobs:
  golangci-lint:
    permissions:
      checks: write
      contents: read
      pull-requests: write 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: change directory
        run: |
          pwd
          cd src
          pwd
      - uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.github_token }}
          go_version: 1.23.0
          reporter: github-pr-review
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
